language: node_js

node_js:
    - "5"

env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libgif-dev

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: pip install --user girder-client

script:
    - npm install
    - npm run lint
    - npm run build
    - npm run build:examples
    - npm run test:unit
    - CANDELA_DUMP_IMAGE=all npm run test:image
    - find src/candela/components -name '*.png' | xargs python script/upload-test-images.py
    - npm run cover
    - npm run codecov
