language: node_js

node_js:
    - "5"

env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libgif-dev

cache:
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
    - npm install
    - npm run build
    - npm run test:unit
    - npm run test:image
