language: node_js

node_js:
    - "5"

env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libgif-dev
    artifacts:
      s3_region: "us-east-1"
      paths:
        - $(find src/candela/components -name '*.png' | tr "\n" ":")
      debug: false

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
    - npm install
    - npm run lint
    - npm run build
    - npm run build:examples
    - npm run test:unit
    - CANDELA_DUMP_IMAGE=all npm run test:image
    - npm run cover
    - npm run codecov
