language: node_js

node_js:
    - "5"

env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libgif-dev

cache:
    directories:
        - node_modules

before_install:
    - npm i -g npm@^2.0.0
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - pip install --user girder-client 'requests[security]'
    - pip install --user flake8

script:
    - npm install
    - npm run lint
    - npm run lint:pycandela
    - npm run build
    - npm run build:examples
    - npm run test:unit
    - CANDELA_DUMP_IMAGE=all npm run test:image
    - find src/candela/components -name '*.png' | xargs python script/upload-test-images.py
    - npm run cover
    - npm run codecov

after_success:
    - npm run dist
    - npm run semantic-release
