import candela from '.';
import './plugins/geojs/load';
import './plugins/glo/load';
import './plugins/lineup/load';
import './plugins/mixin/load';
import './plugins/onset/load';
import './plugins/sententree/load';
import './plugins/similaritygraph/load';
import './plugins/trackerdash/load';
import './plugins/treeheatmap/load';
// import './plugins/upset/load';
import './plugins/vega/load';
