sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - iojs
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test
  - npm run lint
  - npm run check-coverage
after_success:
  - npm run report-coverage
