- name: Clone Girder DB Items repository
  git:
    repo: https://github.com/OpenGeoscience/girder_db_items
    dest: "{{ storage }}/database_assetstore"
    version: "{{ database_assetstore_revision }}"

- name: Clone Candela repository
  git:
    repo: https://github.com/Kitware/candela
    dest: "{{ storage }}/candela"
    version: "{{ candela_revision }}"

# TODO: remove this task and the one after it after setting up Resonant Lab
# to pull candela.js from node_modules for use in the HTML export.
- name: Install Candela node requirements
  command: npm install
  args:
    chdir: "{{ storage }}/candela"
    creates: node_modules

- name: Build Candela
  command: npm run build
  args:
    chdir: "{{ storage }}/candela"
    creates: build/candela/candela.js

- name: Install plugins
  command: "{{ girder_venv }}/bin/girder-install plugin -s --dev {{ storage }}/database_assetstore {{ storage }}/candela/app/resonantlab"
  environment:
    GOOGLE_ANALYTICS_KEY: "{{ google_analytics_key }}"
