---
- hosts: all
  become_user: root
  become_method: sudo
  vars_files:
    - ../vars.yml

  roles:
    - role: girder.girder
      girder_path: "{{ storage }}/girder"
      girder_virtualenv: "{{ girder_venv }}"
      girder_version: "{{ girder_revision }}"

  post_tasks:
    - include: mongo.yml

    - name: Install APT packages
      become: yes
      apt:
        name:
          - python
          - python-dev
          - git
          - libcairo2-dev
          - libjpeg8-dev
          - libpango1.0-dev
          - libgif-dev
          - libffi-dev
          - build-essential
          - g++
          - postgresql
          - postgresql-contrib
          - libpq-dev

    - include: girder-plugin.yml
    - include: girder-setup.yml
