---
- hosts: all
  become_user: root
  become_method: sudo

  tasks:
    - name: Add Mongo repository key
      become: yes
      shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

    - name: Set Mongo package list
      become: yes
      shell: echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

    - name: Pull in latest Node package files
      become: yes
      shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

    - name: Ensure APT packages are installed
      become: yes
      apt:
        name:
          - python
          - python-dev
          - git
          - nodejs
          - mongodb-org
          - libcairo2-dev
          - libjpeg8-dev
          - libpango1.0-dev
          - libgif-dev
          - libffi-dev
          - build-essential
          - g++
          - postgresql
          - postgresql-contrib
          - libpq-dev

    - name: Update pip
      become: yes
      shell: curl https://bootstrap.pypa.io/get-pip.py | python

    - name: Update NPM to latest version
      become: yes
      command: npm i -g npm

    - name: Clone Girder repository
      git:
        repo: https://github.com/girder/girder
        dest: girder
        version: 6bda1a7b65bea1c11187cdeb136877739693f466

    - name: Clone Girder DB Items repository
      git:
        repo: https://github.com/OpenGeoscience/girder_db_items
        dest: girder/plugins/database_assetstore
        version: a530c9546d3ac4f50ec4519ef6c7bb348e2b4bc7

    - name: Install Girder DB Items requirements
      become: yes
      command: pip install -r requirements.txt
      args:
        chdir: girder/plugins/database_assetstore

    - name: Clone Candela repository
      git:
        repo: https://github.com/Kitware/candela
        dest: candela
        version: 5c17f10d754778e7ea291f1f24c290d997e4dec8

    - name: Install Candela node requirements
      command: npm i
      args:
        chdir: candela
        creates: node_modules

    - name: Install Candela python requirements
      become: yes
      command: pip install -r requirements.txt
      args:
        chdir: candela/app/resonant-laboratory

    - name: Install girder-client
      become: yes
      command: pip install -e git+https://github.com/girder/girder.git@6bda1a7b65bea1c11187cdeb136877739693f466#egg=girder

    - name: Build Candela
      command: npm run build
      args:
        chdir: candela
        creates: build/candela/candela.js

    - name: Link Resonant Laboratory into Girder plugin directory
      file:
        src: ~/candela/app/resonant-laboratory
        dest: ~/girder/plugins/resonant-laboratory
        state: link

    - name: Install Girder node requirements
      command: npm i
      args:
        chdir: girder
        creates: node_modules

    - name: Install Girder Python requirements
      become: yes
      command: pip install -r requirements.txt
      args:
        chdir: girder

    - name: Build Girder
      command: ./node_modules/.bin/grunt
      args:
        chdir: girder

    - name: Start MongoDB
      service:
        name: mongod
        state: started

    - name: Install girder_client
      become: yes
      pip:
        chdir: /home/vagrant/girder/clients/python
        extra_args: -e
        name: .

    - name: Install Girder as a service
      become: yes
      copy:
        src: girder.conf
        dest: /etc/init/girder.conf
        mode: 644
        owner: root

    - name: Start Girder
      become: yes
      service:
        name: girder
        state: started
        enabled: yes

    - name: Wait for Girder to start
      wait_for:
        port: 8080
        delay: 1

    - name: Create Girder admin user
      girder:
        port: 8080
        user:
          firstName: Admin
          lastName: User
          login: admin
          password: adminadmin
          email: admin@example.com
          admin: yes
        state: present

    - name: Activate Girder plugins
      girder:
        port: 8080
        username: admin
        password: adminadmin
        plugins:
          - resonant-laboratory
          - database_assetstore
        state: present

    - name: Restart Girder
      girder:
        port: 8080
        username: admin
        password: adminadmin
        put:
          path: system/restart

    - name: Wait for Girder to restart
      wait_for:
        port: 8080
        delay: 5

    - name: Create filesystem assetstore
      girder:
        port: 8080
        username: admin
        password: adminadmin
        assetstore:
          name: Filesystem Assetstore
          type: filesystem
          root: /opt/girder
          current: true
        state: present

    - name: Create database assetstore
      girder:
        port: 8080
        username: admin
        password: adminadmin
        assetstore:
          name: Resonant Laboratory Database Assetstore
          type: database
          dbtype: mongo
          dburi: mongodb://localhost:27017/reslab
        state: present
    
    - name: Upload example data to Girder
      command: python populateGirder.py -p adminadmin
      args:
        chdir: ~/candela/app/resonant-laboratory/scripts
