- name: Add Mongo repository key
  become: yes
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: Set Mongo package list
  become: yes
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: Install Mongo
  become: yes
  apt:
    update_cache: yes
    name:
      - mongodb-org

- name: Start MongoDB
  service:
    name: mongod
    state: started
