---
- hosts: all
  become_user: root
  become_method: sudo
  vars:
    adminuser_firstname: Admin
    adminuser_lastname: User
    adminuser_login: admin
    adminuser_password: adminadmin
    adminuser_email: admin@example.com

    storage: /home/vagrant
    girder_venv: "{{ storage }}/venv"

    girder_revision: 12e12f17a7a8ec99330c16234e19a14435b1a034
    database_assetstore_revision: a530c9546d3ac4f50ec4519ef6c7bb348e2b4bc7
    candela_revision: f823873ab1c11feba09779f82fcb4325b72d33ff
    girder_client_revision: 6bda1a7b65bea1c11187cdeb136877739693f466

    google_analytics_key: ""

  roles:
    - role: girder.girder
      girder_path: "{{ storage }}/girder"
      girder_virtualenv: "{{ girder_venv }}"
      girder_version: "{{ girder_revision }}"

  post_tasks:
    - include: mongo.yml

    - name: Ensure APT packages are installed
      become: yes
      apt:
        name:
          - python
          - python-dev
          - git
          - libcairo2-dev
          - libjpeg8-dev
          - libpango1.0-dev
          - libgif-dev
          - libffi-dev
          - build-essential
          - g++
          - postgresql
          - postgresql-contrib
          - libpq-dev

    - name: Clone Girder DB Items repository
      git:
        repo: https://github.com/OpenGeoscience/girder_db_items
        dest: "{{ storage }}/database_assetstore"
        version: "{{ database_assetstore_revision }}"

    - name: Clone Candela repository
      git:
        repo: https://github.com/Kitware/candela
        dest: "{{ storage }}/candela"
        version: "{{ candela_revision }}"

    # TODO: remove this task and the one after it after setting up Resonant Lab
    # to pull candela.js from node_modules for use in the HTML export.
    - name: Install Candela node requirements
      command: npm install
      args:
        chdir: "{{ storage }}/candela"
        creates: node_modules

    - name: Build Candela
      command: npm run build
      args:
        chdir: "{{ storage }}/candela"
        creates: build/candela/candela.js

    - name: Install plugins
      command: "{{ girder_venv }}/bin/girder-install plugin -s --dev {{ storage }}/database_assetstore {{ storage }}/candela/app/resonantlab"
      environment:
        GOOGLE_ANALYTICS_KEY: "{{ google_analytics_key }}"

    - name: Install girder_client
      become: yes
      command: "pip install -e ."
      args:
        chdir: "{{ storage }}/girder/clients/python"

    - name: Create Girder admin user
      girder:
        port: 8080
        user:
          firstName: "{{ adminuser_firstname }}"
          lastName: "{{ adminuser_lastname }}"
          login: "{{ adminuser_login }}"
          password: "{{ adminuser_password }}"
          email: "{{ adminuser_email }}"
          admin: yes
        state: present

    - name: Activate Girder plugins
      girder:
        port: 8080
        username: "{{ adminuser_login }}"
        password: "{{ adminuser_password }}"
        plugins:
          - resonantlab
          - database_assetstore
        state: present

    - name: Restart Girder
      girder:
        port: 8080
        username: "{{ adminuser_login }}"
        password: "{{ adminuser_password }}"
        put:
          path: system/restart

    - name: Wait for Girder to restart
      wait_for:
        port: 8080
        delay: 5

    - name: Create filesystem assetstore
      girder:
        port: 8080
        username: "{{ adminuser_login }}"
        password: "{{ adminuser_password }}"
        assetstore:
          name: Filesystem Assetstore
          type: filesystem
          root: "{{ storage }}/assetstore/girder"
          current: true
        state: present

    - name: Create database assetstore
      girder:
        port: 8080
        username: "{{ adminuser_login }}"
        password: "{{ adminuser_password }}"
        assetstore:
          name: Resonant Lab Database Assetstore
          type: database
          dbtype: mongo
          dburi: mongodb://localhost:27017/reslab
        state: present

    - name: Upload example data to Girder
      command: "python populateGirder.py -p {{ adminuser_password }}"
      args:
        chdir: "{{ storage }}/candela/app/resonantlab/scripts"
